INSERT INTO vehicle_issues (fault_description, fault, advice) VALUES
(f1, 'Fuel Mixture too Rich', 'Adjust/replace carburetor'),
(f2, 'Greasy Engine oil', 'Change lubrication oil'),
(f3, 'Low battery', 'Charge/Replace battery'),
(f4, 'Leakage from the exhaust', 'Fix leakage/replace'),
(f5, 'Weak clutch plate', 'Replace clutch plates'),
(f6, 'Worn out Brake pads, loose Belt, Wheel bearing failure', 'Adjust/Replace'),
('Non-started cold Engine', 'Flat battery, loose starter connection, battery terminal corrosion', 'Change/replace battery'),
('Black smoke emissions from the tail pipe', 'Solenoid problem, bad rings, bad fuel', 'Adjust/replace pistons or change the complete engine'),
('Clutch not responding', 'Insufficient hydraulic oil, leakage from the dance sleeve', 'Adjust/Replace'),
('When a car turns over but won’t start', 'Check if there is sufficient fuel, spark plug check, check out fuel pump and relay, timing belt, check, clean Air and fuel filters', 'Adjust/Replace'),
('Speedometer not working properly', 'A faulty sensor, Bad wiring or cut cable', 'Replace'),
('Clicking sound when starting a car', 'Battery, terminal corrosion, starter motor problems, loose starter connection', 'Adjust/Replace'),
('Whining noise when accelerating', 'Power steering issues, differential gear issues, engine problems', 'Adjust/Replace'),
('Remote car starter problems', 'Car starter range, battery might be dead, check if the hood is open', 'Adjust/Replace'),
('A glowing LED in the dashboard in form of a battery sign', 'Alternator belt, check for loose connection, Car Alternator problem', 'Adjust/Replace'),
('Whistle sound from the wheel', 'Lack of lubrication, wheel bearing', 'Adjust/Replace'),
('Oil leakage', 'Issues with valve cover and oil filter, issues with oil plug', 'Replace'),
('Smelling fuel in the oil system', 'High fuel pressure, bad fuel pressure regulator', 'Replace'),
('Decreased mileage', 'Bad fuel pressure regulator', 'Replace'),
('Burning of coolant produces a sweet smell', 'Faulty intake manifold gasket', 'Replace'),
('Blue smoke emission', 'When engine oil enters into the engine combustion chamber and burns along with fuel and air mixture', 'Adjust leakage'),
('Green or yellow leaks', 'Coolant leaks', 'Adjust/Replace'),
('Squealing or screeching when you brake', 'Bad brake pads. The brake hardware is worn', 'Replace'),
('Chirping or squealing noise from under the hood', 'Drive belt', 'Replace'),
('Humming, growling, rumbling when driving down the road', 'New tires, new wheel bearing', 'Replace'),
('Rise of engine temperature', 'Overheating, Bad fan', 'Replace'),
('Car jerking', 'Bad plug, bad cabling', 'Change spark plugs or cables'),
('Brownish moisture from the radiator', 'Radiator is dirty', 'Flush radiator and change coolant'),
('Whining noise from the front of your car', 'Bad power steering fluid or low belt tension', 'Adjust/Replace'),
('Engine becomes weak in performance', 'Buildup of carbon deposit in cylinders', 'Adjust/Replace engine'),
('Car shakes and wobbles in gallops', 'Bad shock absorbers', 'Adjust/Replace'),
('Unstable headlight system', 'Bad fuse, bulb, or relay', 'Replace');